;(function(){
document.addEventListener('DOMContentLoaded',function(){
const loginScreen=document.getElementById('login-screen');
const appShell=document.getElementById('app-shell');
const userEl=document.getElementById('auth-email');
const passEl=document.getElementById('auth-password');
const togglePassword=document.getElementById('toggle-password');
const msgEl=document.getElementById('auth-message');
const userBadge=document.getElementById('auth-user-email');
const btnLogin=document.getElementById('btn-login');
const btnRegister=document.getElementById('btn-register')||document.getElementById('link-register');
const btnReset=document.getElementById('btn-reset');
const btnLogout=document.getElementById('btn-logout');
const hintUser=document.getElementById('hint-email');
const hintPassword=document.getElementById('hint-password');
function setMessage(t,k){if(!msgEl)return;msgEl.textContent=t||'';msgEl.style.color=k==='error'?'#b00020':'#00695c'}
function withButtonProgress(btn,text,fn){if(!btn)return fn();const o=btn.innerHTML;btn.disabled=true;btn.classList.add('btn-progress');btn.innerHTML=text||o;const c=()=>{btn.disabled=false;btn.classList.remove('btn-progress');btn.innerHTML=o};return Promise.resolve().then(fn).finally(c)}
function toggleUI(signed){if(signed){if(loginScreen)loginScreen.style.display='none';if(appShell)appShell.style.display='';try{if(window.renderOrgName)window.renderOrgName()}catch{}}else{if(loginScreen)loginScreen.style.display='';if(appShell)appShell.style.display='none'}}
async function hash(s){const enc=new TextEncoder().encode(s);const d=await crypto.subtle.digest('SHA-256',enc);return Array.from(new Uint8Array(d)).map(b=>b.toString(16).padStart(2,'0')).join('')}
const LocalAuth={currentUser:null,_listeners:[],onAuthStateChanged:function(cb){this._listeners.push(cb);try{cb(this.currentUser)}catch{}},_emit:function(){this._listeners.forEach(cb=>{try{cb(this.currentUser)}catch{}})},signInWithUsernameAndPassword:async function(u,p){const q=await window.db.collection('users').where('username','==',u).limit(1).get();if(q.empty)throw new Error('user_not_found');const doc=q.docs[0];const data=doc.data();if(data.isDisabled)throw new Error('user_disabled');const ok=(await hash(p))===String(data.passwordHash||'');if(!ok)throw new Error('wrong_password');this.currentUser={uid:doc.id,username:String(data.username||u),email:String(data.username||u),tenantId:String(data.tenantId||'')};this._emit()},signOut:async function(){this.currentUser=null;this._emit()},createUserWithUsernameAndPassword:async function(u,p){const exists=await window.db.collection('users').where('username','==',u).limit(1).get();if(!exists.empty)throw new Error('user_exists');const ph=await hash(p);const add=await window.db.collection('users').add({username:u,passwordHash:ph,roles:['super_admin','admin'],tenantId:'',createdAt:Date.now()});this.currentUser={uid:add.id,username:u,email:u,tenantId:''};this._emit()}};
window.auth=LocalAuth;
function focusCreateOrgSection(){const el=document.getElementById('btn-create-org');const nameEl=document.getElementById('new-org-name');if(el){try{el.scrollIntoView({behavior:'smooth',block:'center'})}catch{}}if(nameEl){try{nameEl.focus()}catch{}}}
btnRegister&&btnRegister.addEventListener('click',function(e){e.preventDefault();focusCreateOrgSection()});
togglePassword&&togglePassword.addEventListener('click',function(){const isText=passEl&&passEl.getAttribute('type')==='text';if(passEl)passEl.setAttribute('type',isText?'password':'text');togglePassword.textContent=isText?'إظهار':'إخفاء'});
function markError(el,has){if(!el)return;if(has)el.classList.add('input-error');else el.classList.remove('input-error')}
userEl&&userEl.addEventListener('input',()=>markError(userEl,false));
passEl&&passEl.addEventListener('input',()=>markError(passEl,false));
async function login(){const u=(userEl.value||'').trim();const p=passEl.value||'';if(!u||!p){markError(userEl,!u);markError(passEl,!p);setMessage('أدخل اسم المستخدم وكلمة المرور.','error');if(hintUser&&!u)hintUser.textContent='أدخل اسم المستخدم.';if(hintPassword&&!p)hintPassword.textContent='أدخل كلمة المرور.';return}markError(userEl,false);markError(passEl,false);return withButtonProgress(btnLogin,'جارٍ الدخول...',async()=>{try{await window.auth.signInWithUsernameAndPassword(u,p)}catch(e){const code=String(e&&e.message||'');const map={user_not_found:'لا يوجد مستخدم بهذا الاسم.',wrong_password:'كلمة المرور غير صحيحة.',user_disabled:'الحساب معطل.'};setMessage(map[code]||'فشل الدخول.','error')}})}
async function logout(){return withButtonProgress(btnLogout,'جارٍ الخروج...',async()=>{try{await window.auth.signOut();setMessage('تم تسجيل الخروج.','')}catch(e){setMessage('خطأ أثناء تسجيل الخروج.','error')}})}
async function registerOrganization(){const orgNameEl=document.getElementById('new-org-name');const orgUserEl=document.getElementById('new-org-username');const orgPassEl=document.getElementById('new-org-password');const createMsg=document.getElementById('create-org-msg');const btn=document.getElementById('btn-create-org');const orgName=(orgNameEl&&orgNameEl.value||'').trim();const username=(orgUserEl&&orgUserEl.value||'').trim();const password=orgPassEl&&orgPassEl.value||'';if(!orgName||!username||(password||'').length<6){if(createMsg)createMsg.textContent='أدخل اسم المنشأة، اسم مستخدم، وكلمة مرور (6+ أحرف).';return}if(createMsg)createMsg.textContent='';try{const existsU=await window.db.collection('users').where('username','==',username).limit(1).get();const existsE=await window.db.collection('users').where('email','==',username).limit(1).get();if(!existsU.empty||!existsE.empty){if(createMsg)createMsg.textContent='اسم المستخدم/البريد مستخدم بالفعل.';return}}catch{}const run=async()=>{try{const ph=await hash(password);const tRef=await window.db.collection('tenants').add({name:orgName,ownerUsername:username,createdAt:Date.now(),disabled:false,logoUrl:''});await window.db.collection('users').add({username:username,email:username,passwordHash:ph,roles:['super_admin','admin'],tenantId:tRef.id,isDisabled:false,isTenantOwner:true});localStorage.setItem('ORG_NAME',orgName);localStorage.setItem('TENANT_ID',tRef.id);localStorage.setItem('IS_OWNER', String((username||'').toLowerCase()==='malek'));await window.auth.signInWithUsernameAndPassword(username,password);if(createMsg)createMsg.textContent='تم إنشاء المنشأة والحساب.'}catch(e){if(createMsg)createMsg.textContent='فشل إنشاء المنشأة.'}};return withButtonProgress(btn,'جارٍ الإنشاء...',run)}
window.auth.onAuthStateChanged(function(user){if(user){toggleUI(true);if(userBadge)userBadge.textContent=user.username||user.email||user.uid;syncUserRoleLocal(user);if(typeof window.updateDepartmentSelects==='function'){window.updateDepartmentSelects()}if(typeof window.renderEmployees==='function'){window.renderEmployees()}if(typeof window.showScreen==='function'){window.showScreen('employees-screen')}}else{toggleUI(false);if(userBadge)userBadge.textContent='';setMessage('لم يتم تسجيل الدخول.','');try{localStorage.setItem('currentRoles',JSON.stringify(['viewer']))}catch{}localStorage.removeItem('managerDeptId');try{localStorage.removeItem('TENANT_ID');localStorage.removeItem('ORG_NAME');localStorage.removeItem('ORG_LOGO_URL')}catch{}try{if(typeof window.resetInMemoryData==='function')window.resetInMemoryData()}catch{}try{if(typeof window.updateDepartmentSelects==='function')window.updateDepartmentSelects();if(typeof window.updateDashboardStats==='function')window.updateDashboardStats();if(typeof window.renderDepartments==='function')window.renderDepartments();if(typeof window.renderEmployees==='function')window.renderEmployees();if(typeof window.renderGoals==='function')window.renderGoals();if(typeof window.renderPerformanceRecords==='function')window.renderPerformanceRecords();if(typeof window.updateReportTargetSelect==='function')window.updateReportTargetSelect()}catch{}if(typeof window.applyRolePermissions==='function'){window.applyRolePermissions()}}});
async function syncUserRoleLocal(user){try{let snap=await window.db.collection('users').where('username','==',user.username).limit(1).get();if(snap.empty){await window.db.collection('users').add({username:user.username,passwordHash:'',roles:['admin'],tenantId:localStorage.getItem('TENANT_ID')||'',isDisabled:false});snap=await window.db.collection('users').where('username','==',user.username).limit(1).get()}const data=snap.docs[0].data();let roles=Array.isArray(data.roles)&&data.roles.length?data.roles:['viewer'];if(data.isDisabled){setMessage('الحساب معطل.','error');await window.auth.signOut();return}const tenantId=data.tenantId||localStorage.getItem('TENANT_ID')||'';if(tenantId){try{await window.updateOrgFromTenantId(tenantId)}catch{}try{localStorage.setItem('TENANT_ID',String(tenantId))}catch{}try{if(typeof window.loadDataFromStorage==='function')window.loadDataFromStorage()}catch{}}try{localStorage.setItem('currentRoles',JSON.stringify(roles));localStorage.setItem('IS_OWNER', String((user.username||'').toLowerCase()==='malek'))}catch{}try{if(typeof window.applyRolePermissions==='function')window.applyRolePermissions()}catch{}}catch{}}
btnLogin&&btnLogin.addEventListener('click',login);
const btnCreateOrg=document.getElementById('btn-create-org');
btnCreateOrg&&btnCreateOrg.addEventListener('click',function(e){e.preventDefault();registerOrganization()});
btnReset&&btnReset.addEventListener('click',function(){setMessage('إعادة تعيين كلمة المرور غير مدعومة حالياً.','error')});
btnLogout&&btnLogout.addEventListener('click',logout);
[userEl,passEl].forEach(function(el){el&&el.addEventListener('keydown',function(e){if(e.key==='Enter')login()})});
});
})();
